"""Keep the recorded 235e670 WebShop behavior separate from later datasets."""

import hashlib
import json
from dataclasses import asdict, is_dataclass
from pathlib import Path
from types import SimpleNamespace

from selfplay_graph_flowsteer import llm
from selfplay_graph_flowsteer.action_protocol import ActionSpec
from selfplay_graph_flowsteer.application import load_adaptive_config
from selfplay_graph_flowsteer.config import ModelGatewayConfig, ModelRoleConfig
from scripts.formal.probe_webshop_legacy import probe

ROOT = Path(__file__).resolve().parents[1]


def test_original_worker_requests_recovery_staging_and_director_surface():
    # Golden values were generated by running this same probe in the retained
    # clean 235e670 checkout, not by blessing the restored implementation.
    expected = json.loads(
        (ROOT / "tests/fixtures/webshop_235e670_behavior_sha256.json").read_text()
    )
    actual = probe()
    assert set(actual) == set(expected)
    for name, value in actual.items():
        encoded = json.dumps(
            value,
            sort_keys=True,
            ensure_ascii=False,
            default=lambda v: asdict(v) if is_dataclass(v) else str(v),
        )
        assert hashlib.sha256(encoded.encode()).hexdigest() == expected[name], name


def test_formal_webshop_legacy_and_corrected_training_rows_are_retained():
    config = load_adaptive_config(ROOT / "configs/formal_training.toml", validate=False)
    shop = config.canvas.for_dataset("webshop")
    assert config.webshop.compatibility_profile == "m02_merged_identity_v1"
    assert config.webshop.worker_guidance_policy == "merged_checklist_v1"
    assert shop.submission_protocol == "legacy" and shop.action_budget_policy == "phase_split_v1"
    assert config.canvas.worker_usage_policy("webshop") is None
    assert (
        config.webshop.max_initial_calls,
        config.webshop.max_revision_calls,
        config.webshop.max_total_calls,
    ) == (12, 4, 16)
    assert all(
        config.canvas.for_dataset(d).submission_protocol == "unified_task_result_v1"
        for d in ("swe_bench", "alfworld")
    )
    assert len((ROOT / "data/formal/train/webshop.jsonl").read_text().splitlines()) == 444


def test_webshop_gateway_preserves_old_text_interpretation(monkeypatch):
    # Later SWE multi-envelope recovery must not change the restored shopping
    # policy. The legacy flattened response is left to its original decoder.
    items = [{
        "type": "message",
        "role": "assistant",
        "content": [{"type": "output_text", "text": "new interpretation"}],
    }]
    monkeypatch.setattr(
        llm,
        "_openai_response_create",
        lambda *args, **kwargs: SimpleNamespace(
            id="fixture", output_text="legacy text", output=items, usage=None
        ),
    )
    backend = object.__new__(llm.OpenAICompatibleBackend)
    backend.config = ModelGatewayConfig(request_profile="responses_text")
    backend._client_for_request = lambda: None
    with llm.request_dataset("webshop"):
        response = backend._generate_response(
            [],
            role="worker",
            role_config=ModelRoleConfig(api_surface="responses"),
            actions=[ActionSpec("webshop_search", "Search", {"type": "object"})],
            deadline=None,
        )
    assert response.text == "legacy text"
    assert "text_action_protocol" not in response.metadata
